version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: stage-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=stage_DB
    command: mongod --replSet rs0
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
